indent_style = "Visual"

error_on_unformatted = true
brace_style = "PreferSameLine"
enum_discrim_align_threshold = 10

use_small_heuristics = "Max"

condense_wildcard_suffixes = true
fn_single_line = true
format_strings = true
format_macro_matchers = true

imports_indent = "Visual"

merge_imports = false
normalize_comments = true
reorder_impl_items = true

struct_field_align_threshold = 10
struct_lit_single_line = true

trailing_comma = "Never"

match_arm_blocks = false
overflow_delimited_expr = true
use_field_init_shorthand = true

format_doc_comments = true
wrap_comments = true
